spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database;MODE=MySQL
    driver-class-name: org.h2.Driver

jwt:
  secret-key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
  validity-in-milliseconds: 3600000